import { Brand, Dish } from "./types";

export const sampleBrandData: Brand = {
  name: "The Burger Den",
  logo_url: "/images/burger-den-logo.png", // Placeholder path
  cuisine: "American Classic",
  description: "Home of the juiciest burgers and crispiest fries in town. Crafted with love, served with a smile.",
  payment_link: "upi://pay?pa=burgerden@example",
  whatsapp: "9876543210",
  contact: "9876543210",
  location_link: "https://maps.app.goo.gl/example",
  review_link: "https://search.google.com/local/writereview?placeid=example",
  instagram: "https://instagram.com/theburgerden",
  custom: "https://example.com",
  full_menu_pic: "/images/full-menu.jpg"
};

export const sampleDishData: Dish[] = [
  {
    id: "classic-beef-burger",
    category: "Burgers",
    name: "Classic Beef Burger",
    image: "/images/classic-beef.jpg",
    reel: "/reels/classic-beef.mp4",
    description: "A timeless classic. 100% pure beef patty, cheddar cheese, lettuce, tomato, and our secret sauce.",
    price: 250,
    instock: "yes",
    veg: "non-veg",
    tag: "bestseller",
  },
  {
    id: "spicy-chicken-supreme",
    category: "Burgers",
    name: "Spicy Chicken Supreme",
    image: "/images/spicy-chicken.jpg",
    description: "Crispy chicken fillet with a spicy kick, topped with jalapeños and chipotle mayo.",
    price: 280,
    instock: "yes",
    veg: "non-veg",
    tag: "chef's special",
  },
  {
    id: "veggie-delight-burger",
    category: "Burgers",
    name: "Veggie Delight Burger",
    image: "/images/veggie-delight.jpg",
    description: "A delicious and hearty vegetable patty with all the classic fixings.",
    price: 220,
    instock: "yes",
    veg: "veg",
    tag: "new",
  },
  {
    id: "loaded-cheese-fries",
    category: "Sides",
    name: "Loaded Cheese Fries",
    image: "/images/cheese-fries.jpg",
    description: "Our signature crispy fries smothered in melted cheddar and topped with spring onions.",
    price: 180,
    instock: "yes",
    veg: "veg",
    tag: "bestseller",
  },
  {
    id: "onion-rings",
    category: "Sides",
    name: "Onion Rings",
    image: "/images/onion-rings.jpg",
    description: "Golden-fried onion rings served with a tangy dipping sauce.",
    price: 150,
    instock: "no",
    veg: "veg",
    tag: "normal",
  },
  {
    id: "classic-coke",
    category: "Beverages",
    name: "Classic Coke",
    image: "/images/coke.jpg",
    description: "The perfect companion to any burger.",
    price: 80,
    instock: "yes",
    veg: "veg",
    tag: "normal",
  },
];
