CREATE TABLE public.vendor_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_slug text NOT NULL UNIQUE,
  email text UNIQUE,
  backend_type text NOT NULL, -- 'supabase' or 'gsheets'
  supabase_project_id text,
  gsheet_id text,
  imagekit_account_id text NOT NULL,
  membership_fee real DEFAULT 0,
  membership_validity date DEFAULT (now() + '10 days'::interval),
  is_member boolean DEFAULT true,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);