CREATE TABLE public.vendor_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_slug text NOT NULL UNIQUE,
  backend_type text NOT NULL, -- 'supabase' or 'gsheets'
  supabase_project_id text,
  gsheet_id text,
  imagekit_account_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);